-- MySQL Script generated by MySQL Workbench
-- Sun Dec 15 18:55:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema softonica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema softonica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `softonica` DEFAULT CHARACTER SET utf8 ;
USE `softonica` ;

-- -----------------------------------------------------
-- Table `softonica`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(48) NOT NULL,
  `password` CHAR(96) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `failures` BIT(3) NOT NULL DEFAULT 0,
  `locked` BIT(1) NOT NULL DEFAULT 0,
  `active` BIT(1) NOT NULL DEFAULT 1,
  `created` DATETIME NOT NULL,
  `lastlogin` DATETIME NULL,
  `deleted` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'System';


-- -----------------------------------------------------
-- Table `softonica`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`profiles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `name` VARCHAR(48) NOT NULL,
  `title` VARCHAR(255) NULL,
  `description` VARCHAR(1024) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `UserProfile_idx` (`userid` ASC) VISIBLE,
  CONSTRAINT `UserProfile`
    FOREIGN KEY (`userid`)
    REFERENCES `softonica`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Profiling';


-- -----------------------------------------------------
-- Table `softonica`.`verifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`verifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `token` VARCHAR(800) NOT NULL,
  `expire` DATETIME NOT NULL,
  `approved` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `UserVerification_idx` (`userid` ASC) VISIBLE,
  UNIQUE INDEX `token_UNIQUE` (`token` ASC) VISIBLE,
  CONSTRAINT `UserVerification`
    FOREIGN KEY (`userid`)
    REFERENCES `softonica`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'System';


-- -----------------------------------------------------
-- Table `softonica`.`resetpasswords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`resetpasswords` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `token` VARCHAR(800) NOT NULL,
  `expire` DATETIME NOT NULL,
  `approved` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `UserResetPassword_idx` (`userid` ASC) VISIBLE,
  CONSTRAINT `UserResetPassword`
    FOREIGN KEY (`userid`)
    REFERENCES `softonica`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'System';


-- -----------------------------------------------------
-- Table `softonica`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `message` VARCHAR(512) NOT NULL,
  `created` DATETIME NOT NULL,
  `read` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `UserNotification_idx` (`userid` ASC) VISIBLE,
  CONSTRAINT `UserNotification`
    FOREIGN KEY (`userid`)
    REFERENCES `softonica`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'System';


-- -----------------------------------------------------
-- Table `softonica`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profileid` INT NOT NULL,
  `type` BIT(8) NOT NULL,
  `name` VARCHAR(48) NOT NULL,
  `created` DATETIME NOT NULL,
  `lastactivity` DATETIME NULL,
  `deleted` DATETIME NULL,
  `active` BIT(1) NOT NULL DEFAULT 1,
  `locked` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `ProfileAccount_idx` (`profileid` ASC) VISIBLE,
  CONSTRAINT `ProfileAccount`
    FOREIGN KEY (`profileid`)
    REFERENCES `softonica`.`profiles` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Economy';


-- -----------------------------------------------------
-- Table `softonica`.`transactioncategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`transactioncategories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(96) NOT NULL,
  `description` TEXT NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Economy';


-- -----------------------------------------------------
-- Table `softonica`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `accountid` INT NOT NULL,
  `categoryid` INT NOT NULL,
  `amount` DOUBLE NOT NULL,
  `created` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  `realized` BIT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `AccountTransaction_idx` (`accountid` ASC) VISIBLE,
  INDEX `TransactionCategory_idx` (`categoryid` ASC) VISIBLE,
  CONSTRAINT `AccountTransaction`
    FOREIGN KEY (`accountid`)
    REFERENCES `softonica`.`accounts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `TransactionCategory`
    FOREIGN KEY (`categoryid`)
    REFERENCES `softonica`.`transactioncategories` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Economy';


-- -----------------------------------------------------
-- Table `softonica`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NULL,
  `name` VARCHAR(48) NOT NULL,
  `background` CHAR(8) NOT NULL,
  `foreground` CHAR(8) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `UserOwnedTag_idx` (`userid` ASC) VISIBLE,
  CONSTRAINT `UserOwnedTag`
    FOREIGN KEY (`userid`)
    REFERENCES `softonica`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Common';


-- -----------------------------------------------------
-- Table `softonica`.`assignedtags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`assignedtags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` BIT(8) NOT NULL,
  `tagid` INT NOT NULL,
  `targetid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `AssignedTag_idx` (`tagid` ASC) VISIBLE,
  CONSTRAINT `AssignedTag`
    FOREIGN KEY (`tagid`)
    REFERENCES `softonica`.`tags` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Common';


-- -----------------------------------------------------
-- Table `softonica`.`skilltypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`skilltypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(96) NOT NULL,
  `description` TEXT NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Profiling';


-- -----------------------------------------------------
-- Table `softonica`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `typeid` INT NOT NULL,
  `name` VARCHAR(96) NOT NULL,
  `description` TEXT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `SkillType_idx` (`typeid` ASC) VISIBLE,
  CONSTRAINT `SkillType`
    FOREIGN KEY (`typeid`)
    REFERENCES `softonica`.`skilltypes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Profiling';


-- -----------------------------------------------------
-- Table `softonica`.`experiences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`experiences` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profileid` INT NOT NULL,
  `skillid` INT NOT NULL,
  `time` TIMESTAMP NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `SkillExperience_idx` (`skillid` ASC) VISIBLE,
  INDEX `ProfileExperience_idx` (`profileid` ASC) VISIBLE,
  CONSTRAINT `ProfileExperience`
    FOREIGN KEY (`profileid`)
    REFERENCES `softonica`.`profiles` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `SkillExperience`
    FOREIGN KEY (`skillid`)
    REFERENCES `softonica`.`skills` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Profiling';


-- -----------------------------------------------------
-- Table `softonica`.`projecttypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`projecttypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(48) NOT NULL,
  `description` TEXT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Projects';


-- -----------------------------------------------------
-- Table `softonica`.`projectcategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`projectcategories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(96) NOT NULL,
  `description` TEXT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Projects';


-- -----------------------------------------------------
-- Table `softonica`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `typeid` INT NOT NULL,
  `categoryid` INT NOT NULL,
  `name` VARCHAR(96) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `ProjectType_idx` (`typeid` ASC) VISIBLE,
  INDEX `ProjectCategory_idx` (`categoryid` ASC) VISIBLE,
  CONSTRAINT `ProjectType`
    FOREIGN KEY (`typeid`)
    REFERENCES `softonica`.`projecttypes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `ProjectCategory`
    FOREIGN KEY (`categoryid`)
    REFERENCES `softonica`.`projectcategories` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Projects';


-- -----------------------------------------------------
-- Table `softonica`.`contributors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`contributors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `projectid` INT NOT NULL,
  `profileid` INT NOT NULL,
  `joined` DATETIME NOT NULL,
  `left` DATETIME NULL,
  `owner` BIT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ProjectContributor_idx` (`projectid` ASC) VISIBLE,
  INDEX `ProfileContributor_idx` (`profileid` ASC) VISIBLE,
  CONSTRAINT `ProjectContributor`
    FOREIGN KEY (`projectid`)
    REFERENCES `softonica`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `ProfileContributor`
    FOREIGN KEY (`profileid`)
    REFERENCES `softonica`.`profiles` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Projects';


-- -----------------------------------------------------
-- Table `softonica`.`marketplaces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`marketplaces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `accountid` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `AccountMarketplace_idx` (`accountid` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `AccountMarketplace`
    FOREIGN KEY (`accountid`)
    REFERENCES `softonica`.`accounts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Economy';


-- -----------------------------------------------------
-- Table `softonica`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marketplaceid` INT NOT NULL,
  `name` VARCHAR(96) NOT NULL,
  `description` TEXT NOT NULL,
  `value` DOUBLE NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `ProductMarketplace_idx` (`marketplaceid` ASC) VISIBLE,
  CONSTRAINT `ProductMarketplace`
    FOREIGN KEY (`marketplaceid`)
    REFERENCES `softonica`.`marketplaces` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Economy';


-- -----------------------------------------------------
-- Table `softonica`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marketplaceid` INT NOT NULL,
  `name` VARCHAR(96) NOT NULL,
  `description` TEXT NOT NULL,
  `value` DOUBLE NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `ServiceMarketplace_idx` (`marketplaceid` ASC) VISIBLE,
  CONSTRAINT `ServiceMarketplace`
    FOREIGN KEY (`marketplaceid`)
    REFERENCES `softonica`.`marketplaces` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Economy';


-- -----------------------------------------------------
-- Table `softonica`.`subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`subscriptions` (
  `id` INT NOT NULL,
  `accountid` INT NOT NULL,
  `serviceid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `AccountSubscription_idx` (`accountid` ASC) VISIBLE,
  INDEX `ServiceSubscription_idx` (`serviceid` ASC) VISIBLE,
  CONSTRAINT `AccountSubscription`
    FOREIGN KEY (`accountid`)
    REFERENCES `softonica`.`accounts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `ServiceSubscription`
    FOREIGN KEY (`serviceid`)
    REFERENCES `softonica`.`services` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Economy';


-- -----------------------------------------------------
-- Table `softonica`.`badges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`badges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `icon` BINARY NOT NULL,
  `name` VARCHAR(96) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Profiling';


-- -----------------------------------------------------
-- Table `softonica`.`achievements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`achievements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profileid` INT NOT NULL,
  `badgeid` INT NOT NULL,
  `created` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `ProfileAchievement_idx` (`profileid` ASC) VISIBLE,
  INDEX `AchievementBadge_idx` (`badgeid` ASC) VISIBLE,
  CONSTRAINT `ProfileAchievement`
    FOREIGN KEY (`profileid`)
    REFERENCES `softonica`.`profiles` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `AchievementBadge`
    FOREIGN KEY (`badgeid`)
    REFERENCES `softonica`.`badges` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Profiling';


-- -----------------------------------------------------
-- Table `softonica`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ownerid` INT NOT NULL,
  `name` VARCHAR(96) NOT NULL,
  `description` TEXT NULL,
  `created` DATETIME NOT NULL,
  `lastactivity` DATETIME NULL,
  `deleted` DATETIME NULL,
  `locked` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `TeamOwner_idx` (`ownerid` ASC) VISIBLE,
  CONSTRAINT `TeamOwner`
    FOREIGN KEY (`ownerid`)
    REFERENCES `softonica`.`profiles` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Social';


-- -----------------------------------------------------
-- Table `softonica`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`members` (
  `id` INT NOT NULL,
  `teamid` INT NOT NULL,
  `profileid` INT NOT NULL,
  `owner` BIT(1) NOT NULL DEFAULT 0,
  `joined` DATETIME NOT NULL,
  `left` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `MemberTeam_idx` (`teamid` ASC) VISIBLE,
  INDEX `MemberProfile_idx` (`profileid` ASC) VISIBLE,
  CONSTRAINT `MemberTeam`
    FOREIGN KEY (`teamid`)
    REFERENCES `softonica`.`teams` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `MemberProfile`
    FOREIGN KEY (`profileid`)
    REFERENCES `softonica`.`profiles` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Social';


-- -----------------------------------------------------
-- Table `softonica`.`repositories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`repositories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `projectid` INT NOT NULL,
  `name` VARCHAR(96) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `notes` TEXT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `RepositoryProject_idx` (`projectid` ASC) VISIBLE,
  CONSTRAINT `RepositoryProject`
    FOREIGN KEY (`projectid`)
    REFERENCES `softonica`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Projects';


-- -----------------------------------------------------
-- Table `softonica`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profileid` INT NOT NULL,
  `targetid` INT NOT NULL,
  `content` TEXT NOT NULL,
  `added` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `ProfileComment_idx` (`profileid` ASC) VISIBLE,
  CONSTRAINT `ProfileComment`
    FOREIGN KEY (`profileid`)
    REFERENCES `softonica`.`profiles` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Social';


-- -----------------------------------------------------
-- Table `softonica`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profileid` INT NOT NULL,
  `targetid` INT NOT NULL,
  `value` BIT(6) NOT NULL,
  `added` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ProfileRating_idx` (`profileid` ASC) VISIBLE,
  CONSTRAINT `ProfileRating`
    FOREIGN KEY (`profileid`)
    REFERENCES `softonica`.`profiles` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Social';


-- -----------------------------------------------------
-- Table `softonica`.`pucharses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`pucharses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marketplaceid` INT NOT NULL,
  `accountid` INT NOT NULL,
  `amount` INT NOT NULL,
  `unit` BIT(8) NOT NULL,
  `when` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `PucharseMarketplace_idx` (`marketplaceid` ASC) VISIBLE,
  INDEX `AccountMarketplace_idx` (`accountid` ASC) VISIBLE,
  CONSTRAINT `PucharseMarketplace`
    FOREIGN KEY (`marketplaceid`)
    REFERENCES `softonica`.`marketplaces` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `AccountMarketplace`
    FOREIGN KEY (`accountid`)
    REFERENCES `softonica`.`accounts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Economy';


-- -----------------------------------------------------
-- Table `softonica`.`forums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`forums` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `creator` INT NOT NULL,
  `title` VARCHAR(96) NOT NULL,
  `description` TEXT NULL,
  `created` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `ForumCreator_idx` (`creator` ASC) VISIBLE,
  CONSTRAINT `ForumCreator`
    FOREIGN KEY (`creator`)
    REFERENCES `softonica`.`profiles` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Social';


-- -----------------------------------------------------
-- Table `softonica`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `forumid` INT NOT NULL,
  `profileid` INT NOT NULL,
  `content` VARCHAR(1024) NOT NULL,
  `added` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `PostForum_idx` (`forumid` ASC) VISIBLE,
  INDEX `PostProfile_idx` (`profileid` ASC) VISIBLE,
  CONSTRAINT `PostForum`
    FOREIGN KEY (`forumid`)
    REFERENCES `softonica`.`forums` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `PostProfile`
    FOREIGN KEY (`profileid`)
    REFERENCES `softonica`.`profiles` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Social';


-- -----------------------------------------------------
-- Table `softonica`.`releases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`releases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `projectid` INT NOT NULL,
  `title` VARCHAR(96) NOT NULL,
  `description` TEXT NULL,
  `testing` BIT(1) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `ProjectRelease_idx` (`projectid` ASC) VISIBLE,
  CONSTRAINT `ProjectRelease`
    FOREIGN KEY (`projectid`)
    REFERENCES `softonica`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Projects';


-- -----------------------------------------------------
-- Table `softonica`.`collaborations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softonica`.`collaborations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `projectid` INT NOT NULL,
  `title` VARCHAR(96) NOT NULL,
  `description` TEXT NOT NULL,
  `form` BIT(8) NOT NULL COMMENT 'Forma współpracy',
  `website` VARCHAR(255) NULL,
  `wiki` VARCHAR(255) NULL,
  `platform` VARCHAR(255) NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  `active` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `ProjectCollaboration_idx` (`projectid` ASC) VISIBLE,
  CONSTRAINT `ProjectCollaboration`
    FOREIGN KEY (`projectid`)
    REFERENCES `softonica`.`projects` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Projects';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
